Make all sendable structs (de)serializable
sztomi/dap-rs pull request #21
Opened 2023-08-03 10:47 UTC by nuid64

#20 related.
Just added a couple of attributes.
Also, can't `fromstr_deser!` and `tostr_ser!` macros be replaced with `derive` attribute macro? Do these macros do something important that I don't suspect?

2023-08-03 17:56 UTC, sztomi commented
> can't fromstr_deser! and tostr_ser! macros be replaced with derive attribute macro

If your question is about replacing these macros with `derive(Deserialize)` and `derive(Serialize)` then the answer is no. The DAP specification often uses typescript union types with literals and `string`. We can represent this as an enum in Rust, but the deserialization has to be custom, since we need to handle the "other" case as well as the translation from the string representation to the enum variants without explicit discriminants. One such example:

```rust 
#[derive(Debug, Clone)]
pub enum PathFormat {
  Path,
  Uri,
  Other(String),
}

impl FromStr for PathFormat {
  type Err = Infallible;

  fn from_str(s: &str) -> Result<Self, Self::Err> {
    match s {
      "path" => Ok(PathFormat::Path),
      "uri" => Ok(PathFormat::Uri),
      other => Ok(PathFormat::Other(other.to_string())),
    }
  }
}

fromstr_deser! {PathFormat}
```

Also, I found that it's useful to provide a `FromStr` implementation. Then it followed that it's useful to reuse that for the deserialization.

If instead you mean coming up with a derive macro that accomplished the same, I'd love that. I just didn't know enough about proc macros at the time I wrote this code (I still don't tbh, although I could reasonably review such code). 

Unless I'm missing some `serde` magic that allows doing the above without any custom code, in which case this code should be replaced with that.

2023-08-03 17:57 UTC, sztomi commented
As for the overall idea, I support making the library client-capable. However, this should be a crate feature that is disabled by default and code that concerns it (such as the derive macros in this PR) should be applied conditionally only.

2023-08-04 06:12 UTC, nuid64 commented
> If your question is about replacing these macros with `derive(Deserialize)` and `derive(Serialize)`

Yes, my question was about this. I did a little search and found that a macro `#[serde(untagged)` on `Other(String)` variant is just what we needed.

Full version:
```
#[serde(rename_all = "camelCase")]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PathFormat {
    Path,
     Uri,
     #[serde(untagged)]
     Other(String),
}
```

2023-08-04 06:17 UTC, nuid64 commented
> However, this should be a crate feature that is disabled by default

This crate makes life easier by just mapping DAP structures to Rust structures and enabling smooth conversions between them. I think prioritizing this as the main goal, with client/server code as a bonus, will be a sensible approach.

2023-08-04 06:38 UTC, nuid64 commented
> ```
> #[serde(rename_all(serialize = "snake_case", deserialize = "PascalCase"))]
> ```
Also we should deserialize to PascalCase, since Rust Structs and Enums have such naming.

2023-08-04 08:45 UTC, nuid64 commented
Passing all 76 tests. Thanks for them, it would be a living hell to make sure everything okay without tests.
Should we remove `gen_enum_from_strings.py` script and the macros?

2023-08-04 11:40 UTC, sztomi commented
I think it might be reasonable to add a few new, targeted tests that checks the serialization and deserialization of these enums. 

> Should we remove gen_enum_from_strings.py script and the macros?

The macros, yes. But the script should stay because I still want the `FromStr` implementations. I don't expect that it will be used too much in the future, but it might be useful if a large struct or enum is added. It's not a very smart script but remove a good chunk of the busywork. Maybe it would make sense to update it use `serde(untagged)` for these variants.

2023-08-06 12:25 UTC, nuid64 commented
Sorry for the mess, was trying to rename branch name👀

2023-08-10 04:09 UTC, nuid64 commented
Those two tests I added should be enough because all the enums have the same structure and differ only in names and "tagged" variants. What do you think?

2023-08-10 11:41 UTC, sztomi commented
@nuid64 I don't see any tests being added, unless I'm missing something. Also, for the new derives, please add a crate feature similar to `integration_testing` in Cargo.toml and apply them as `cfg_attr`. By default, this should be turned off.

2023-08-11 14:06 UTC, nuid64 commented
These tests were introduced in commit [84ac086](https://github.com/sztomi/dap-rs/pull/21/commits/84ac08606c95b81666639ea0a63cb365893c88a8)

2023-08-12 17:39 UTC, sztomi commented
@nuid64 Ah yes, sorry; it looks like github folded the diff so I couldn't see those.

2023-08-16 10:47 UTC, nuid64 commented
Sorry, problem appeared in specific adapter

2023-08-16 10:54 UTC, sztomi commented
No worries, just do your thing and let me know when this is ready for a review.

2023-08-17 06:18 UTC, nuid64 commented
I rechecked my needs and I think `dap-rs` can be used for client code with current changes and this PR review-ready.

2023-08-17 11:08 UTC, sztomi commented
Alright. Please rebase your branch and rewrite the commit history to get rid of merge commits and reverts. Fixup commits like "fix typos" should be squashed with the original commit they belong to. You will likely want to do an interactive rebase for this.

2023-08-20 18:14 UTC, sztomi requested changes
There is a merge commit again (you should rebase the branch instead of `git merge` - let me know if you need assistance with that). But first, let's get the macro removal in.

2023-08-20 18:14 UTC, sztomi commented on dap/src/base_message.rs
> +#[derive(Deserialize, Serialize, Debug)]
All of these should be `cfg_attr`s for a new feature (e.g. `client`)

2023-08-20 18:14 UTC, sztomi commented on dap/src/macros.rs
I think it would be better to do the removal of these macros in a separate PR before this is removed.

2023-08-21 08:03 UTC, nuid64 commented on dap/src/base_message.rs
> +#[derive(Deserialize, Serialize, Debug)]
I don't see why types cannot be usable by both sides as default. I'm finding this approach more convenient than including this as a feature, and compile time increases insignificantly (<2%).

2023-08-21 08:05 UTC, nuid64 commented
> There is a merge commit again (you should rebase the branch instead of `git merge` - let me know if you need assistance with that). But first, let's get the macro removal in.

I did a rebase. Apparently, I did a merge after it and forgot to clean it.


UPD:
Ah, it's because of conflict with main branch. I wonder why it happened only with that one poor file. I have tried to "return in the past and resolve merge conflict back then", but now there is another merge conflict.

2023-08-22 09:12 UTC, sztomi commented on dap/src/base_message.rs
> +#[derive(Deserialize, Serialize, Debug)]
Compile times and binary size both increases. The library is already very chunky. I would prefer a feature for this because using the library this way is essentially a DAP client feature which only has a handful of potential users such as Helix and Lapce (all of whom already have their own bespoke DAP implementation). Do you have a different use-case?

2023-08-22 18:00 UTC, nuid64 commented on dap/src/base_message.rs
> +#[derive(Deserialize, Serialize, Debug)]
Library may look chunky if build it from project's root directory (dap-rs), because with `dap` `integration_testing` are builded, too, along with it's dependencies. But `dap` itself compiles three times faster and crates, that are using `dap-rs`, will compile only `dap`, actually.
I think people make frontends more often. And I've not seen a libraries that divide the use of _types_ on client and server, so this separation can be confusing and weird.

2023-08-22 19:19 UTC, sztomi commented on dap/src/base_message.rs
> +#[derive(Deserialize, Serialize, Debug)]
No, I'm purely referring to the build size of the library when I'm saying it's chunky. It is currently 8 MB in a release build. On your branch it is 14MB. That is a non-trivial increase to an already large size. I'd like this to be optional.

2023-08-23 03:33 UTC, nuid64 commented on dap/src/base_message.rs
> +#[derive(Deserialize, Serialize, Debug)]
Hm, you're right. Okay then

2023-08-24 15:21 UTC, sztomi commented
@nuid64 do you want me to rebase your branch? Are you planning to land the macro deletion first?

2023-08-25 05:01 UTC, nuid64 commented
Yeah, go ahead

2023-09-05 03:18 UTC, nuid64 commented
How is it going?

2023-09-18 16:39 UTC, sztomi approved these changes

2023-09-18 16:43 UTC, sztomi commented
@nuid64 sorry it took so long. I decided to squash the entire thing into one commit because the individual commits were not viable (tests were not building or passing) and I'd rather have one large commit than potentially unbuildable commits when bisecting something in the future. Thanks for your contribution! Will you open another PR with the removal of the custom macros?

2023-09-18 16:43 UTC, merged

2023-10-03 00:19 UTC, qwe-q commented
Hi everyone, I'm using dap-rs in a project and would just like you to know that this patch fixed a bug with the ``Scope`` struct and probably a bunch of others too. [Here](https://github.com/sztomi/dap-rs/commit/c8900bd8efa7fb51b76bba875f8b5caf9127f361#diff-05501a1166884a7905a0dd5bed94de535231a5c69e91514f8dad8d9cd7979fc3R1113) (You have to expand the diff for ``types.rs``) you can see that an erroneous serialization in snake case and not camel case was removed.

Thanks for taking care of this! Updating to the latest crate version made this problem simply go away :)